# Site settings
title: Todd Swift
twitter_username: toddvocado
name: Todd Swift

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.stachedknowledge.com/blog
 - title: GitHub
   url: https://github.com/toddswift
 - title: StackOverflow
   url: https://stackexchange.com/users/15765132/tswift
 - title: DZone
   url: https://dzone.com/users/3649009/toddvocado.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/toddswift/

#Any buzzword skills you want to include
skills:
 - Lean
 - Agile
 - Coaching
 - Scaled Agile Framework (SAFe)
 - Scrum (PSM)
 - Kanban
 - XP
 - Waterfall
 - PMI
 - Enterprise Transformation
 - Agile Testing
 - Strategic Planning
 - Organizational Change
 - Entrepreneurial Leadership
 - Business Development
 - Software Delivery
 - Process Improvements
 - Conflict Resolution
 - Workshop Facilitation
 - Value Stream Mapping
 - Gap Analysis
 - Communication
 - Quality Control
 - Quality Assurance
 - Statistical Process Control
 - Relentless Improvement
 - Six Sigma
 - Business Analysis
 - Systems Analysis
 - Technical Writing
 - Proposals
 - Risk Management
 - Project Management
 - PCI Compliance
 - Feature Driven Development
 - Behavior Driven Development (BDD)
 - Acceptance Test Drive Development (ATDD)
 - Test Driven Development (TDD)
 - Contract Driven Development (CDD)
 - Agile Modeling
 - Unified Modeling Language (UML)
 - Business Process Modeling Notation (BPMN)
 - Training and Facilitation
 - Mural
 - ScaledAgile Weave
 - Azure DevOps
 - Jira (including numerous addons and plug ins)
 - Agile Craft (Jira Align)
 - Confluence
 - Git
 - Swift Kanban
 - Kabanize
 - GitHub
 - Bitbucket
 - Bamboo CI/CD
 - Agility Health Radar
 - JFrog Artifactory
 - Jenkins
 - Cucumber TeamCity
 - Slack
 - AWS
 - LeanKit
 - Miro
 - Trello
 - Pega 7
 - Azure
 - Azure DevOps
 - Microsoft Dynamics 365 CRM
 - Power BI
 - Niku/Clarity
 - Visual Studio
 - JavaScript
 - VB6
 - C#
 - Visual Basic
 - HTML5
 - CSS
 - Eclipse
 - Java
 - IntelliJ IDEA
 - Kotlin
 - MySQL
 - SQL
 - Photoshop
 - Visio
 - Source Safe
 - all Microsoft Office applications
 - SharePoint 
 - Microsoft Project
 - Project Online/Server
 - Product management

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://www.stachedknowledge.com/feed.xml

#Work experience is required
roles:
 - title: Agile Coach
   start: 2019
   end: 2020
   employer: cPrime
   description: Serve as a member of the Lean Agile Center of Excellence which helps optimize and sustain Agile transformation accross the enterprise.
 - title: Agile Coach
   start: 2019
   end: 2019
   employer: Apex Systems
   description: I am proud to serve as a mentor/advisor, trainer, and consultant while coaching multiple teams to adopt mindsets and methods that deliver  sustainable value in the shortest possible lead time throughout Enterprise transformations. I am passionate to help individuals and teams to  incorporate new learnings into their daily work and apply agile and lean thinking to the specific environment and impediments they will face.
 - title: Owner and Lean Agile Instructor
   start: 2018
   end: Ongoing
   employer: Stached Knowledge
   description: Stached Knowledge was established as an educational provider of Lean Agile course ware and workshops, providing weekend training to the public
 - title: Agile Coach
   start: 2017
   end: 2019
   employer: Sogeti / Capgemini
   description: TBD
 - title: Senior Agile Project Manager
   start: 2017
   end: 2017
   employer: Guilford Group
   description: TBD.
 - title: Senior Agile Project Manager
   start: 2014
   end: 2017
   employer: Defenders
   description: TBD.
 - title: Agile Project Manager
   start: 2005
   end: 2014
   employer: Guilford Group
   description: TBD.
 - title: Automation Engineer
   start: 2005
   end: 2005
   employer: Pilkington
   description: TBD.
 - title: Software Engineer
   start: 2003
   end: 2005
   employer: Flexware Innovation
   description: TBD.
 - title: Software Engineer
   start: 2002
   end: 2003
   employer: Koch LLC
   description: TBD.
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2002
   subject: Computer Integrated Manufacturing Technology
   school: Purdue University


#List of interesting Github repo/projects to include - optional
github:
 - toddswift/toddswift.github.io
 - toddswift/SAFeAzureDevOpsServerTemplate
 - toddswift/worldretroday.github.io
 - toddswift/official-guide
 - toddswift/moq4
 

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/11375750/tswift
   flairimageurl: https://stackoverflow.com/users/flair/11375750.png?theme=clean
intro: |
  Passionate servant leader rooted in Lean-Agile principles that exemplifies the core values of Alignment, Built-In Quality, Transparency, and Program Execution.
  Extensive experience in all aspects of cultural change, transformation, and relentless improvement.  
  Deep history of working with IT Development, Operations, Project Management, Procurement, Human Resources, Legal, Marketing, and Regulatory. 
  Background includes driving continuous improvement and strengthening an organizations Lean-Agile practices by partnering with leadership to stand up and sustain guiding coalitions, Centers of Excellence, and Communities of Practices.
  Strong relationship building skills that have established long lasting partnerships between IT and business leaders at all levels. 
  Successfully built, launched, managed and led numerous multi-million-dollar, global cross-functional Agile Release Trains with the ability to plan and align a 40000+ company through a Lean-Agile transformation.
  Proven success from C-Level to Team Level. A passionate, lifelong learner and contributor through teaching, speaking, mentoring, workshop facilitation, conferences, certifications and collaborative partnerships. 
  My lifelong dream is to teach SAFe® courses in Latin America and Spain; and increase awareness in Lean Agile frameworks to native Spanish speakers. 
  In my spare time, my wife and I represent Subaru as Brand Ambassadors ♡, educating the public on improving environmental practices and the benefits of Subaru ownership. (♻)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Azure DevOps, Bitbucket, Bamboo, Maven, Sonar, Jenkins, JFrog, Docker , etc. I also have experience with an array of testing tools and technologies. (Seleniumm, JUnit, nUnit, etc.)<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Python, Kotlin, and cloud platforms such as Azure/AWS. <br/><br/>
   
   I write a blog discussing adopting Lean Agile mindsets that can be found here: <a target='_blank' href="https://www.stachedknowledge.com/blog">stachedknowledge.com/blog</a>
